# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dafd197723cd7dffce10345421d7920e49110b91799405de909dfd5eb1b301406f0dab474e33ec9b2d32cb7f15b89e0c95342cc80faf79b09dcfc1b275519dc3

test:
  secret_key_base: dd994be7dcceef87b500912ba1e9bcf1bdcc132df5ef09a131b7c8a10aa7b3c5fb9f96eed5c2e9d020d310d81fb8b7824879a6ed2a104b78a63646126c93d0f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
